---
- name: Deploiement de NGINX
  hosts: all
  become: yes

  tasks:
    - name: 1) apt mise à jour 
      ansible.builtin.apt:
        update_cache: yes

    - name: 2) nginx installation
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: 3) démarage du service et activation au boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes